// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICFmRTzp49pdL5xVhE31bM8-MkEX3ins',
    appId: '1:623126320460:web:844464db8b269accdd2be9',
    messagingSenderId: '623126320460',
    projectId: 'startwatch-ing',
    authDomain: 'startwatch-ing.firebaseapp.com',
    storageBucket: 'startwatch-ing.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByoX4nh8NUCnYbDFRBgXz_6chkuMhorMQ',
    appId: '1:623126320460:android:a8fd74228ac1bf82dd2be9',
    messagingSenderId: '623126320460',
    projectId: 'startwatch-ing',
    storageBucket: 'startwatch-ing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCxPSvAWMy71kIHDTZPWjNOVp_2DPTZw',
    appId: '1:623126320460:ios:13a92e8b7be2e935dd2be9',
    messagingSenderId: '623126320460',
    projectId: 'startwatch-ing',
    storageBucket: 'startwatch-ing.firebasestorage.app',
    androidClientId: '623126320460-tgf4sca02bgh733lso68k710d2iqjcli.apps.googleusercontent.com',
    iosClientId: '623126320460-alneed5ualmn2gl4kpjrh3a507lggrhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.startwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlCxPSvAWMy71kIHDTZPWjNOVp_2DPTZw',
    appId: '1:623126320460:ios:13a92e8b7be2e935dd2be9',
    messagingSenderId: '623126320460',
    projectId: 'startwatch-ing',
    storageBucket: 'startwatch-ing.firebasestorage.app',
    androidClientId: '623126320460-tgf4sca02bgh733lso68k710d2iqjcli.apps.googleusercontent.com',
    iosClientId: '623126320460-alneed5ualmn2gl4kpjrh3a507lggrhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.startwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCICFmRTzp49pdL5xVhE31bM8-MkEX3ins',
    appId: '1:623126320460:web:4d02634ee76b4495dd2be9',
    messagingSenderId: '623126320460',
    projectId: 'startwatch-ing',
    authDomain: 'startwatch-ing.firebaseapp.com',
    storageBucket: 'startwatch-ing.firebasestorage.app',
  );

}